<template>
  <v-dialog v-model="dialog" persistent max-width="500px" transition="none">
    <v-card :loading="isSubmitLoading">
      <v-toolbar density="compact">
        <v-spacer></v-spacer>
        <v-btn icon @click="close">╳</v-btn>
      </v-toolbar>
      <v-card-title>{{ labelFormTitle }}</v-card-title>
      <v-expand-transition>
        <div v-show="alert.show">
          <v-alert rounded="0" :type="alert.type">
            {{ alert.message }}
          </v-alert>
        </div>
      </v-expand-transition>
      <v-form
        ref="form"
        @submit.prevent="addOrEditEntity"
        :disabled="isSubmitLoading"
      >
        <v-card-text>
          <v-row>
            <v-col cols="12">
              <v-text-field
                label="Name"
                v-model.trim="entity.name"
                :rules="[rules.required, rules.max(200)]"
              ></v-text-field>
            </v-col>
            <v-col cols="12">
              <v-text-field
                label="Details"
                v-model.trim="entity.details"
                :rules="[rules.max(500)]"
                counter="500"
              ></v-text-field>
            </v-col>
            <v-col cols="12">
              <v-checkbox
                :false-value="0"
                :true-value="1"
                hide-details
                v-model="entity.isEnabled"
                label="Is Enabled?"
              ></v-checkbox>
              <p>
                If disabled, the kiosk won't be able to interact with the ATS,
                i.e. inserting Attendance Entries will be prohibited.
              </p>
            </v-col>
            <v-col cols="12">
              <v-checkbox
                :false-value="0"
                :true-value="1"
                hide-details
                v-model="entity.shouldResetLocalDBOnStartup"
                label="Reset local DB on next startup?"
              ></v-checkbox>
              <p>
                If enabled, the kiosk will wipe its' own Activities log upon
                next startup. This won't affect the data that you have here.
                After the machine wipes its' local records, the option will
                revert back to being unchecked (showing 'No' in the table).
              </p>
            </v-col>
          </v-row>
        </v-card-text>
        <v-card-actions class="justify-center">
          <v-btn
            size="large"
            :loading="isSubmitLoading"
            color="info"
            type="submit"
            >{{ labelBtnSubmit }}</v-btn
          >
        </v-card-actions>
      </v-form>
    </v-card>
  </v-dialog>
</template>
<script>
import { rules } from "../stores/rules";
import { determineErrMessageInAlert } from "../errHandler";
import KioskService from "../services/KioskService";

export default {
  emits: ["done"],
  data() {
    return this.initialState();
  },
  methods: {
    initialState() {
      return {
        componentModeIsAdd: true,
        rules: rules,
        alert: {
          show: false,
          type: "info",
          message: null,
        },
        dialog: false,
        isSubmitLoading: false,
        entity: {
          id: null,
          name: null,
          details: null,
          isEnabled: 1,
          shouldResetLocalDBOnStartup: 0,
        },
      };
    },
    showAlert(pType, pMessage) {
      this.alert = {
        show: true,
        type: pType,
        message: pMessage,
      };
    },
    resetAlert() {
      this.alert = {
        show: false,
        type: "info",
        message: null,
      };
    },
    async addOrEditEntity() {
      this.resetAlert();
      const { valid } = await this.$refs.form.validate();
      if (!valid) {
        return;
      }
      this.isSubmitLoading = true;
      if (this.componentModeIsAdd) {
        await this.add();
      } else {
        await this.edit();
      }
      this.isSubmitLoading = false;
    },
    async add() {
      try {
        const res = await KioskService.add(this.entity);
        if (res.status == 200) {
          this.close();
          this.$emit("done");
          //user inserts a kiosk -> sys admin sees the autogenerated id -> sys admin prepares app build for the new kiosk
        }
      } catch (err) {
        this.handleErr(err);
      }
    },
    async edit() {
      try {
        const res = await KioskService.edit(this.entity);
        if (res.status == 200) {
          this.close();
          this.$emit("done");
        }
      } catch (err) {
        this.handleErr(err);
      }
    },
    close() {
      Object.assign(this.$data, this.initialState());
    },
    open(entity) {
      if (!entity) {
        this.componentModeIsAdd = true;
      } else {
        this.componentModeIsAdd = false;
        this.entity = Object.assign({}, entity);
      }
      this.dialog = true;
    },
    handleErr(err) {
      const msg = determineErrMessageInAlert(err);
      this.showAlert("error", msg);
    },
  },
  computed: {
    labelFormTitle() {
      return this.componentModeIsAdd ? "Register a new kiosk!" : this.entity.id;
    },
    labelBtnSubmit() {
      return this.componentModeIsAdd ? "Add" : "Edit";
    },
  },
};
</script>
